// Seletores globais
const headerContainer = document.getElementById('header-container');
const footerContainer = document.getElementById('footer-container');
const searchInput = document.getElementById('searchInput');
const shareButton = document.getElementById('shareButton');
const limparDadosBtn = document.getElementById('limparDados');
const tabelaProdutos = document.getElementById('tabelaProdutos');
const grupoProduto = document.getElementById('grupoProduto');
const btnApenasCadastrados = document.getElementById('btnApenasCadastrados');
const btnTodosProdutos = document.getElementById('btnTodosProdutos');

let apenasCadastradosAtivado = false;

const produtosIniciais = [
    { nome: 'CREME CHANTILLY GRAN FINALE FLEISCHMANN SPRAY 12UNI 250G', grupo: 'AB MAURI' },
    { nome: 'CREME CHANTILLY GRAN FINALE FLEISCHMANN TP 27UNI 200ML', grupo: 'AB MAURI' },
    { nome: 'CREME CROCANTE OVOMALTINE 10PTX100G', grupo: 'AB MAURI' },
    { nome: 'CREME CROCANTE OVOMALTINE PET 12X260G', grupo: 'AB MAURI' },
    { nome: 'FERMENTO BIOL SECO FLEISCHMANN 12DPX23X10G', grupo: 'AB MAURI' },
    { nome: 'FERMENTO BIOL SECO FLEISCHMANN 4DPX69X10G', grupo: 'AB MAURI' },
    { nome: 'MELHORADOR FAR MAIS MACIO FLEISCHMANN 6DPX32X10G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM AIPIM 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM BROWNIE 20X400G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM CHOCOMOUSSE 400G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM COCO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM LARANJA CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM LIMAO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM MILHO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CHOCOLATE 390G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 12X190G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 12X300G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE ROCKS 6DPX18X40G', grupo: 'AB MAURI' },
    { nome: 'AMENDOIM DADINHO CROCKS CEBOLA E SALSA 24X90G', grupo: 'DADINHO' },
    { nome: 'AMENDOIM DADINHO CROCKS CHURRASCO 24X90G', grupo: 'DADINHO' },
    { nome: 'AMENDOIM DADINHO CROCKS PIMENTA 24X90G', grupo: 'DADINHO' },
    { nome: 'AMENDOIM DADINHO CROCKS TRADICIONAL 24X90G', grupo: 'DADINHO' },
    { nome: 'DADINHO TRAD SACHE 40X90G', grupo: 'DADINHO' },
    { nome: 'DADINHO TRIBOMBOM AVELA 15X12X30G', grupo: 'DADINHO' },
    { nome: 'PAÇOCA DADINHO QUADRADA EMBR 12X40X20G', grupo: 'DADINHO' },
    { nome: 'PAÇOCA DADINHO ZERO QUADRADA 8DPX24UNX18G', grupo: 'DADINHO' },
    { nome: 'TRENTO BITES AO LEITE 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES AVELA 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES BCO-DARK 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES DARK 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES DUO 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES MOUSSE MARACUJA 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES TORTA LIMAO 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MASSIMO BRANCO C/ COOKIES 8DPX15UNX25G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MASSIMO CHOCOLATE 8DPX15UNX25G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MASSIMO DUO 8DPX15UNX25G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO SPECIALE AVELAS AO LEITE 8DISPX12UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO SPECIALE AVELAS BRANCO 8DISPX12UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO SPECIALE PISTACHE C/AVELAS 8DISPX12UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER AVELAS 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CHEESECAKE DE MORANGO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CHOCOLATE 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CHOCOLATE BRANCO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER DARK 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER DUO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER MOUSSE MARACUJA 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER PISTACHE 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER TORTA LIMAO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'NUTRATA BARRA CHARGE 6X12UNX45G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR BEIJINHO 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR BRIGADEIRO 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR BROWNIE HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR DOCE DE LEITE HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR MORANGO COM CHANTILLY 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO COOKIES & CREAM 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA YOPRO CHOCOLATE 6X12UNX55G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA YOPRO MORANGO 6X12UNX55G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PROTO WAFER SABOR DOCE DE LEITE HAVANNA 4X12UNX30G', grupo: 'NUTRATA' },
    { nome: 'ADOCANTE ADOCYL LIQ SACARINA 12X100ML', grupo: 'HYPERA' },
    { nome: 'ADOCANTE ADOCYL LIQ SACARINA 12X200ML', grupo: 'HYPERA' },
    { nome: 'ADOCANTE ADOCYL LIQ STEVIA 80ML', grupo: 'HYPERA' },
    { nome: 'ADOCANTE ZERO CAL LIQ SACARINA 12X100ML', grupo: 'HYPERA' },
    { nome: 'ADOCANTE ZERO CAL LIQ SACARINA 12X200ML', grupo: 'HYPERA' },
    { nome: 'BEBIDA FUNC ENGOV AFTER CITRUS 6X250ML', grupo: 'HYPERA' },
    { nome: 'BEBIDA FUNCIONAL ENGOV AFTER TANGERINA 6X250ML', grupo: 'HYPERA' },
    { nome: 'AMENDOIM DORI CONF CHOCOLATE 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI JAPONES 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI TORRADO SALG S/PELE 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA BOLETE TUTTI FRUTTI 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA GOTA COLA 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA HORTELA MINT 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA LUA CHEIA CHANTILLY 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA LUA CHEIA FRUTAS 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA TRINK FRUTAS 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA YOGURTE100 MORANGO 36X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET JELLY BEANS 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET JELLY BEANS 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI AMENDOIM CHOC CONF 6X18X39G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI AMENDOIM CHOC CONF POUCH 30X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE BRANCO CONF 4X16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE BRANCO CONF 6X18X40G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE CONF 4X16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE CONF 6X18X40G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI VICEVERSA CHOC CONF 6X18X40G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI VICEVERSA CHOCOLA CONF 4X16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA AMORA 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BANANA 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BEIJO 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BOCA 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA MINHOCA 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA MINHOCA ÁCIDA 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA URSO 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.PESC.GIRAFA FRAMBOESA 2X30X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.PESCOÇO GIRAFA MORANGO 2X30X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.TUBO YOGURTE100 ÁCID.REC 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGA.TUBO MORANGO ÁCIDO RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ FLOR 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TIJOLO 16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO MORANGO RECH.12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO UVA ÁCIDO RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO YOGURTE100 RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS FRUTAS SORTIDAS DP 12X30X32G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA ANEL ACIDO 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA SINO 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRAN CONFEITARTE GOURMET +CACAU 20X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRAN CONFEITARTE TIJOLINHO TRAD 20X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRANULADO CHOCOLATE DORI 30X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRANULADO CHOCOLATE MESCLAD DORI 30X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRANULADO DORI CHOC 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'MINI DISQUETI CHOCOLATE CONF 4X16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'PIRULITO BOLETE MAST 12X50X11,2G', grupo: 'DORI ALIMENTOS' },
    { nome: 'PIRULITO YOGURTE100 MOR. MAST 12X50X11,2G', grupo: 'DORI ALIMENTOS' },
    { nome: 'ACUCAR MASCAVO VITAO 500G F12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'AVEIA FLOCOS FINOS S/ GLUTEN VITAO 12X170G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'AVEIA FLOCOS FINOS VITAO 12X170G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'AVEIA FLOCOS FINOS VITAO 12X400G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'AVEIA FLOCOS GROSSOS VITAO 12X170G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BEIJINHO ZERO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BRIGADEIRO ZERO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CACAU EM PO VITAO 100G F12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHIA EM GRAOS VITAO 120G F12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC BRANCO MARCANTE MOR CRANBERRY VITAO 4X6X70G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC DARK MARCANTE NIBS ZERO VITAO 4X6X70G 70% CACAU', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC LEITE MARCANTE ZERO VITAO 4X6X70G 40% CACAU', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES INTEGRAL CACAU VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES INTEGRAL CASTANHA DE CAJU VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES INTEGRAL CASTANHA DO PARA VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CREME DE AVELA VEGANO ZERO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DOCE DE LEITE ZERO PURO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'PSYLLIUM 100G F12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'AGUA DESMINERALIZADA TECBRIL 12X1L', grupo: 'BASTON' },
    { nome: 'DESO ABOVE FEEL FREE ZERO S/ALU MEN 12X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ABOVE FEEL FREE ZERO S/ALU WOMEN 12X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMA WOMEN CLAREADOR 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL MEN 96H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL S/PERF 96H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL WOMEN 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS CANDY 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS DOLCE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS FRESH 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS LADY 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CLAS S/PERFUME 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CREAM ORIGINAL 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CREAM VANILLA 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS CARBON ACTIVE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS HURRICANE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS OCEAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS VULCAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTR INVISIBLE MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME BLACK MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME MOV MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME SPORT MEN 72H AL 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE INVISIBLE WOMAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE MAXX CREAM ORIGINAL L250ML P150ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE SPORT ENERGY MEN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE SPORT ENERGY WOMAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'ESPUMA BARBA ABOVE 24X150ML/145G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET ACAO TOTAL 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON ACAO TOTAL 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON CITRONELA 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON S/CHEIRO 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECONOMICA EUCALIPTO 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET PROMOCIONAL 12X450ML/330G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET PROMOCIONAL S/CHEIRO 12X450ML/330G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET S/CHEIRO 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR CAPIM LIMAO 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR LAVANDA 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR NEUTRO 12X250ML', grupo: 'BASTON' },
    { nome: 'SABONETE INTIMO ABOVE 12X200ML', grupo: 'BASTON' },
    { nome: 'SABONETE INTIMO ABOVE PACKS DUO 200ML 12UN', grupo: 'BASTON' },
    { nome: 'TALCO ANTISSEPTICO ABOVE PE PROT TRADIC 12X100G', grupo: 'BASTON' },
    { nome: 'CHUPA CHUPS TRIO SORTIDO 6DPX20X29G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA CHEWY SOUR 16STX24DPX40G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA MAST MELANCIA 40GX16STX24DP', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA MAST. MORANGO VIT. C 10X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA SWIRL CARAMELO 10X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA SWIRL MORANGO VIT.C 10X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA SWIRL MOUSSE MARACUJA 12DPX15 41G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS COOL WHITE TUTTI FRESH (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS COOL WHITE BLUE RASPBERRY (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA FRESH MINT 28X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA MORANGO 28X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA P.FRESH MELANCIA 6DPX6X56G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA P.WHITE SPEARMINT 6DPX6X56G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA UP 2U 28X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA WTERGREEN 28X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS MINT LTA 50X12 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS MORANGO LTA 50X12 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS TUTTI FRUTTI LTA 12X12X35G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS XTREME LTA 50X12 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK FRUIT 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK FRUTAS VERMELHAS 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK MINT 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK MORANGO/IOG 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK RAINBOW 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK TUTTI FRUTTI 14X16 C/ 24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK WILDSPEARMINT 14X16 C/24', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH FRUIT (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH MINT (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH SPEARMINT (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH STRONG (3 CAM+) 5X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    // DORI ALIMENTOS - Produtos novos
    { nome: 'AM DORI TORRA BOTECO LASCAS ALHO 36X90G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AM DORI TORRA BOTECO LASCAS CEB 36X90G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AM DORI TORRA BOTECO SALGADO 12X320G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AM DORI TORRA BOTECO SALGADO 36X90G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AM PETTIZ TSSP LEMON PEPPER 20X320G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AM PETTIZ TSSP LEMON PEPPER 36X110G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM CHOCOLATE DORI CONF. 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM CHOCOLATE DORI CONF. 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM COLORIDO DORI CONF 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM COLORIDO DORI CONF. 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI CHOCOLATE 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI CHOCOLATE 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI COLORIDO 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI COLORIDO CONF. 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI COLORIDO CONF. 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI JAPONES 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI JAPONES 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI JAPONES 36X200G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM DORI JAPONES CART 10X5X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM JAPONES DORI 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM JAPONES DORI 20X320G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM JAPONES DORI 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ CEB/SALSA CRO 12X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ CEBOL/SALSA CROC 16X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ CEBOL/SALSA CROC 24X350G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ CEBOL/SALSA CROC 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ CEBOL/SALSA CROC 36X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ NATURAL CROCANTE 16X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ NATURAL CROCANTE 24X350G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ NATURAL CROCANTE 30X50G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ NATURAL CROCANTE 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ NATURAL CROCANTE 36X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIME.VER CRO 12X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIMENTA VER CRO 16X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIMENTA VER CROC 24X350G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIMENTA VER CROC 30X50G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIMENTA VER CROC 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ PIMENTA VER CROC 36X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL JAPON 12X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL JAPONES 16X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL JAPONES 24X350G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL JAPONES 36X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL TSSP 12X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ SPECIAL TSSP 36X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'AMENDOIM PETTIZ TORRA.SAL S/PELE 24X320G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA BOLETE DORI TUTTI FRUTTI 30X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA BOLETE TUTTI FRUTTI 24X400G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA DORI DURA HORTELA 30X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA DORI DURA RECH MORANGO 30X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA DORI YOGURTE MORANGO 24X400G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA LUA CHEIA DORI RECH FRUTAS 24X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'BALA YOGURTE DORI MAST. MORANGO 24X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'CARTELA AMENDOIM COLOR DORI CONF 12X5X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET ACIDO 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET ACIDO CONF 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET ACIDO CONF 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET FRUTAS 9X24X16G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET FRUTAS CONF 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET JELLY BEANS 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DELIKET JELLY BEANS 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOC. LEITE CONF 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOC.BRANCO CONF POUCH 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE BRANCO CONF 4X16X60G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE BRANCO CONF 9X24X18G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE CONF 10X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE CONF 9X24X18G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI CHOCOLATE CONF POUCH 30X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI MINI CHOC. AO LEITE 12X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DISQUETI V/VERSA CHOC CONF POUCH 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA AMORA 12X12X13G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BANANA 10X230G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BEIJO 10X230G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA BOCA 10X230G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI GELATINA MINHOCA 12X12X13G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG. T.RECH MORANGO 12X12X17G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG. T.RECH MORANGO ÁCIDO 12X12X17G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.PESC.GIRAFA FRAMBOESA 2X30X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.PESC.GIRAFA YOGURTE100 2X30X30G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REG.T.RECH YOGURT100 ÁCID 12X12X17G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ BOLETE SOUR 2X24X27G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO MORANGO RECH.12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO UVA ÁCIDO RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGALIZ TUBO YOGURTE100 RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'DORI REGA.TUBO MORANGO ÁCIDO RECH 12X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS ANEL DE FRUTAS ÁCIDAS 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS ANEL FRUTAS ACIDO 14X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA AMERICANA FRUTAS 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA CORACAO 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA CORACAO 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA GOMOS DE FRUTAS 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA GOMOS DE FRUTAS 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA MINHOCA ACIDA 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA MINHOCA ACIDA 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA MINHOCA FRUTAS 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA MINHOCA FRUTAS 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA SINO 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA TUBO FRUTAS 30X3X32G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA URSO 12X700G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMA URSO 36X150G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMAS SORTIDAS 20X500G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMAS SORTIDAS 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMAS SORTIDAS 30X70G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS GOMAS SORTIDAS10X1KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS IOGURTE DP 12X30X32G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS MINHOCA DE FRUTAS 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS MINHOCA FRUTAS ACIDA 14X600G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS TUBO CREME FRUTAS 12X30X32G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GOMETS URSO DE FRUTAS 30X100G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRANULADO CONFEITO COLORIDO DORI 30X120G', grupo: 'DORI ALIMENTOS' },
    { nome: 'GRANULADO CHOCOLATE DORI 8X1,010KG', grupo: 'DORI ALIMENTOS' },
    { nome: 'JUBES F.SNACKS HIPNOSE FRAMBOESA12X20X48G', grupo: 'DORI ALIMENTOS' },
    { nome: 'JUBES F.SNACKS HIPNOSE MORANGO 12X20X48G', grupo: 'DORI ALIMENTOS' },
    { nome: 'JUBES FRUIT SNACKS TROP. TUBO 12X20X48G', grupo: 'DORI ALIMENTOS' },
    { nome: 'MINI DISQUETI CHOCOLATE CONF 9X36X11G', grupo: 'DORI ALIMENTOS' },
    { nome: 'PIRULITO DORI BOLETE T.FRUTTI 20X400G', grupo: 'DORI ALIMENTOS' },
    { nome: 'PIRULITO FRUTSY FRAMBO. MAST 12X50X11,2G', grupo: 'DORI ALIMENTOS' },
    { nome: 'PIRULITO YOGURTE100 MOR. MAST 30X105G', grupo: 'DORI ALIMENTOS' },
    { nome: 'REGALIZ UVA OLEADO 70G', grupo: 'DORI ALIMENTOS' },
    // LINDT
    { nome: 'BOMBONS SORTIDOS LINDT LINDOR CORNET 16UNID 200G', grupo: 'LINDT' },
    { nome: 'CAIXA BOMBONS SORTIDOS LINDT LINDOR CORNET C/6UNID 75G', grupo: 'LINDT' },
    { nome: 'CAIXA DE CHOCOLATE LINDOR SORTIDA 100G', grupo: 'LINDT' },
    { nome: 'CAIXA PRESENTE LINDT LINDOR CHOC AO LEITE C/ 9UNID 112G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT EXCELLENCE TABLETE 70% DARK 100G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT EXCELLENCE TABLETE 85% DARK 100G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT EXCELLENCE TABLETE 90% DARK 100G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT EXCELLENCE TABLETE DARK FLOR DE SAL 100G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT EXCELLENCE TABLETE EXTRA CREMOSO AO LEITE 100G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT GOLD TABLETE AO LEITE 300G', grupo: 'LINDT' },
    { nome: 'CHOCOLATE LINDT TABLETE PISTACHE 100G', grupo: 'LINDT' },
    { nome: 'LATA PRESENTE LINDT LINDOR TRUFAS AO LEITE 4UNID 50G', grupo: 'LINDT' },
    { nome: 'LINDOR CORNET AO LEITE 75G', grupo: 'LINDT' },
    { nome: 'LINDOR SINGLES AO LEITE COM AVELA 12X100G', grupo: 'LINDT' },
    { nome: 'LINDT CLASSIC AO LEITE 12X100G', grupo: 'LINDT' },
    { nome: 'LINDT CREATION CREME BRULEE 14X150G', grupo: 'LINDT' },
    { nome: 'LINDT GOLD BAR AO LEITE COM AVELÃS 300G', grupo: 'LINDT' },
    { nome: 'LINDT GOLD BUNNY AO LEITE 125G', grupo: 'LINDT' },
    { nome: 'LINDT GOLD BUNNY AO LEITE 32X50G', grupo: 'LINDT' },
    { nome: 'LINDT LINDOR CORNET AO LEITE 37G', grupo: 'LINDT' },
    { nome: 'LINDT LINDOR CORNET AO LEITE 8X16UNID 200G', grupo: 'LINDT' },
    { nome: 'LINDT LINDOR CORNET PISTACHE 200G', grupo: 'LINDT' },
    { nome: 'LINDT LINDOR SINGLES 60% DARK 100G', grupo: 'LINDT' },
    { nome: 'LINDT LINDOR SINGLES AO LEITE 100G', grupo: 'LINDT' },
    { nome: 'LINDT OVO DE PASCOA SORTIDO 6X137G', grupo: 'LINDT' },
    { nome: 'LINDT SWISS CLASSIC AO LEITE COM AVELA 12X100G', grupo: 'LINDT' },
    { nome: 'LINDT SWISS CLASSIC TABLETE BRANCO 12X100G', grupo: 'LINDT' },
    { nome: 'LINDT SWISS CLASSIC TABLETE DARK 100G', grupo: 'LINDT' },
    // HYPERA
    { nome: 'ADOÇANTE ADOCYL LIQ STEVIA 12XL160MLP140ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ADOCYL LIQ SUCRALOSE 12X160ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ADOCYL LIQ SUCRALOSE 12X80ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ADOCYL PO CULINARIO 6X150G', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ ERITRITOL 12X65ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ ERITRITOL PACK 6X2X65ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ STEVIA 12X80ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ STEVIA PROMO 2X80ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ SUCRALOSE 100ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ SUCRALOSE PROM 2X100ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL LIQ XILITOL 12X65ML', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL PÓ ASPARTAME DP 12X50X600MG', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL PÓ ERITRITOL POTE 6X250G', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL PÓ STEVIA DP 12X50X800MG', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL PÓ SUCRALOSE DP 12X50X600MG', grupo: 'HYPERA' },
    { nome: 'ADOÇANTE ZERO CAL PÓ SUCRALOSE DP L100P75X600MG', grupo: 'HYPERA' },
    { nome: 'BEBIDA FUNC ENGOV AFTER BERRY VIBES 6X250ML', grupo: 'HYPERA' },
    { nome: 'BEBIDA FUNC ENGOV AFTER PINK LEMONADE 6X250ML', grupo: 'HYPERA' },
    { nome: 'BEBIDA FUNC ENGOV AFTER RED HITS 6X250ML', grupo: 'HYPERA' },
    // VITAO ALIMENTOS
    { nome: 'BANANADA ZERO COB AMARGO VITAO 12DPX3UNX22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BANANADA ZERO VITAO POTE 12X270G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC ARROZ AMEND AMAR NATURATTA 96X40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC ARROZ INTEG COB. CHOC MEIO AMARGO NATURATTA 24X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC ARROZ INTEG COB. F. VERMELHAS NATURATTA 24X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC ARROZ NEGRO NATURATTA 20X90G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC ARROZ PASTA AMEND CHOC BRANCO NATURATTA 96X40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC MULTIGRÃOS NATURATTA 20X90G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC TAPIOCA COB COCO NATURATTA 24X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'BISC TAPIOCA ZERO COB CHOC NATURATTA 24X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC BRANCO COOKIES AND CREAM MARCANTE ZERO VITAO 4X6X70G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC BRANCO MARCANTE CAPPUCCINO ZERO VITAO 4X6X70G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC BRANCO MARCANTE VEGANO ZERO VITAO 48X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC CAFE EXPRESSO MARCANTE ZERO VITAO 4X6X70G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC LEITE CEREAIS ZERO VITAO 48X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC LEITE MARCANTE ZERO VITAO 4DPX12X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC MEIO AMARGO MARCANTE ZERO VITAO 4DPX12X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC S LACTOSE MARCANTE ZERO VITAO 4DPX12X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOC ZERO MARCANTE 70% AMARGO 48X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCOLATE BRANCO MARCANTE ZERO VITAO 4DPX12X22G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCOLATE VITAO SOUL PRO AO LEITE ZERO 6X12UNX40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCOLATE VITAO SOUL PRO BRANCO ZERO 6X12UNX40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCOLATE VITAO SOUL PRO MEIO AMARGO ZERO 6X12UNX40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCONERD ROLINHO WAFER AO LEITE ZERO 6DPX15X25G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'CHOCONERD ROLINHO WAFER M AMARGO ZERO 6DPX15X25G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COB BRANCA VEGANA ZERO VITAO 10X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COB CHOCOLATE BRANCO ZERO VITAO 10X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COCADA AO LEITE ZERO MARACUJA VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COCADA AO LEITE ZERO VITAO 8X200GR', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES INTEGRAL CHOCOLATE VITAO 26X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES SEM GLUTEN BAUNILHA VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES SEM GLUTEN CACAU VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES SEM GLUTEN CASTANHA DO PARA VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES SEM GLUTEN CHOCOLATE VITAO 26X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES SEM GLUTEN TRAD VITAO 26X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO BANANA COB CHOCO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO BANANA VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO CAST PARA VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO CHOCOLATE VITAO 26X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO MACA E CANELA COB CHOCO VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO MORANGO COB CHOCO VITAO 8X120G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'COOKIES ZERO TRADICIONAL VITAO 26X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY BALLS CEREAL CHOC S GLUTEN 14X150G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY BOLINHO S GLUTEN GOT CHOC 4X12X35G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY BOLINHO S GLUTEN MORANGO 4X12X35G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY CEREAL ARGOLINH S GLUTEN 14X150G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY CEREAL DUO CHOC S GLUTEN 14X150G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY CEREAL NATURAL S GLUTEN 14X150G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY COOKIES S GLUTEN BAUNILHA 20X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY COOKIES S GLUTEN CACAU Z 20X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY COOKIES S GLUTEN MORANG 20X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY MOANA BISCOITO CHOC 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY MOANA BISCOITO COCO 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY ROLINHO WAFER CHOC ZERO 28X25G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY ROLINHO WAFER MORAN ZERO 28X25G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY ROLINHO WAFER ZERO 28X25G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY ROSQUINHA S GLUTEN CHOC 20X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY ROSQUINHA S GLUTEN LEITE 20X60G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY SNACKS S GLUTEN CHEDDAR 24X30G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY SNACKS S GLUTEN PIZZA 24X30G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY SNACKS S GLUTEN REQUEIJAO 24X30G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY STAR WARS BISCOITO CHOC 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY STAR WARS BISCOITO LEITE 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY TOY STORY BISCOITO COCO 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DISNEY TOY STORY BISCOITO MORANGO 40G C/20', grupo: 'VITAO ALIMENTOS' },
    { nome: 'DOCE DE LEITE ZERO C/ COCO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'FARINHA DE ARROZ VITAO 10X300G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'FARINHA DE AVEIA SEM GLUTEN VITAO 12X170G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'FARINHA MIX SEM GLUTEM 400G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'FECULA DE BATATA VITAO 12X300G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'FECULA DE MANDIOCA VITAO 10X300G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GELEIA 100% FRUT VERMELHAS DELAKASA 8X180G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GELEIA ZERO UVA VITAO 8X180G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GOIABADA ZERO VITAO POTE 12X270G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA PROTEICA SOULPRO BANANA E CACAU 12X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA PROTEICA SOULPRO TRADICIONAL 12X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA S/ GLUTEN TRADICIONAL VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA SEM GLUTEN TRAD ZERO VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD FRUTAS TROPICAIS VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD FRUTAS VERMELHAS VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD ORIGINAL VITAO 6X800G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD SAB CAMPO VITAO 12X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD ZERO VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRAD ZERO VITAO 6X800G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRADICIONAL CACAU COCO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRADICIONAL CACAU COCO 6X800G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRADICIONAL GRAOS E SEMENTES 6X800G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA TRADICIONAL ORIGINAL VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'GRANOLA ZERO BANANA E CACAU VITAO 12X250G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'LEITE CONDENSADO ZERO VITAO 8X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'MIX BOLO SEM GLUTEN CHOCOLATE VITAO 12X300G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'MIX DE GRAOS E SEMENTES VITAO 120G F12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'MIX PAO SEM GLUTEN TRADICIONAL VITAO 12X300G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'PROTEINA DE SOJA VITAO 12X200G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA INTEG ZERO CHOCOLATE VITAO 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA INTEG ZERO LEITE 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA INTEGRAL CHOCOLATE VITAO 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA INTEGRAL LEITE VITAO 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA S/ GLUTEN CHOCOLATE VITAO 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'ROSQUINHA S/ GLUTEN LEITE VITAO 20X110G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'SAL MARINHO VITAO 1 KG F10', grupo: 'VITAO ALIMENTOS' },
    { nome: 'SEMENTE DE LINHACA DOURADA 150G FD12', grupo: 'VITAO ALIMENTOS' },
    { nome: 'SNACKS INTEGRAL CHEDDAR KIDS VITAO 24X40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'SNACKS INTEGRAL PIZZA KIDS VITAO 24X40G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'VICCIO ROLL Z CHOC AVELA VITAO 4X10X30G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'VICCIO ROLL Z CHOC LEITE VITAO 4X10X30G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'WAFER INTEGRAL CHOCOLATE ZERO VITAO 20X90G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'WAFER INTEGRAL MORANGO ZERO VITAO 20X90G', grupo: 'VITAO ALIMENTOS' },
    { nome: 'WAFER INTEGRAL TORTA LIMAO ZERO VITAO 20X90G', grupo: 'VITAO ALIMENTOS' },
    // NUTRATA
    { nome: 'COLLAGEN JOINTS COMPLEX TYPE II NUTRATA 300G', grupo: 'NUTRATA' },
    { nome: 'COLLAGEN PURE NUTRATA 300G', grupo: 'NUTRATA' },
    { nome: 'COLLAGEN SUN NUTRATA 300G', grupo: 'NUTRATA' },
    { nome: 'NATURAL FIBER 200G NUTRATA', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA BACIO DI LATTE CARAMELO SALGADO 6X12UNX45G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA BACIO DI LATTE PISTACCHIO 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA BACIO DI LATTE PISTACCHIO 6X9UNX70G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA CARAMELO DARK 6X12UNX45G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA CARAMELO TRADICIONAL 6X12UNX45G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA CHARGE DARK 6X12UNX45G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR BANOFFEE HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR BROWNIE HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR DULCE DE LECHE E MORANGO HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR DULCE DE LECHE HAVANNA E LIMAO SICILIANO 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR MOUSSE DE MARACUJA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO BAR TORTA DE LIMAO 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA GREGO COOKIES & CREAM 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA PROTO CRUNCH CHOCOLATE DARK 6X10UNX60G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA PROTOBAR AMENDO WHEY 6X9UNX70G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA PROTOBAR HAVANNA BROWNIE DE CHOCOLATE COM DULCE DE LECHE 6X9UNX70G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA PROTOBAR SABOR DOCE DE LEITE HAVANNA 6X9UNX70G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA YOPRO CAPPUCCINO 6X12UNX55G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA BARRA ZERO D. LEITE HAVANNA 6X12UNX40G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA CREATINA MONOHIDRATADA CREATIN UP 300G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA CREATINA MONOHIDRATADA REFIL 300G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA CREATINA MONOHIDRATADA UP 100G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA AMENDOIM DULCE DE LECHE CREAM HAVANNA 600G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA AMENDOIM DULCE DE LECHE CRUNCHY HAVANNA 600G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA AMENDOIM LEITE TRUFADO 600G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA AMENDOIM PACOCA 600G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA AMENDOIM PISTACHE 400G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PASTA DE AMENDOIM COOKIES & CREAM 600G', grupo: 'NUTRATA' },
    { nome: 'NUTRATA PROTO WAFER SABOR CHOCOLATE BELGA 4X12UNX30G', grupo: 'NUTRATA' },
    { nome: 'OMEGA 3 NUTRATA CAPS 60X6', grupo: 'NUTRATA' },
    { nome: 'OMEGA ULTRA TG CAP NUTRATA 60X6', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO BEIJINHO NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO BEIJINHO REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO BRIGADEIRO NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO BRIGADEIRO REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO DOCE DE LEITE C/ CHOC HAVANNA NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO IOGURTE NATURAL NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO MORANGO COM CHANTILLY NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO MORANGO COM CHANTILLY REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY GREGO VITAMINA DE FRUTAS NUTRATA 450G', grupo: 'NUTRATA' },
    { nome: 'WHEY NPRO 100% BAUNILHA REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY NPRO 100% CHOCOLATE REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY NPRO 100% MORANGO REFIL NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY ZERO LACTOSE BAUNILHA NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY ZERO LACTOSE SABOR CHOCOLATE NUTRATA 900G', grupo: 'NUTRATA' },
    { nome: 'WHEY ZERO LACTOSE SABOR MORANGO NUTRATA 900G', grupo: 'NUTRATA' },
    // PECCIN SA
    { nome: 'BALA FRUTIBELO FRAMBOESA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA FRUTIGUTI SORTIDA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA PECCIN FRUTIBELO FRAMBOESA 20PCTX600G', grupo: 'PECCIN SA' },
    { nome: 'BALA PECCIN FRUTIGUTI SORTIDA 20PCTX600G', grupo: 'PECCIN SA' },
    { nome: 'BALA PECCIN MENTA 20PCTX600G', grupo: 'PECCIN SA' },
    { nome: 'BALA PECCIN ZAZÁ SORTIDA 20PCTX600G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA 2 FRUTAS SORTIDA 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA 2 FRUTAS SORTIDA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA FRAMBOESA 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MINI 2 FRUTAS SORTIDA 12DPX12X30G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MINI FRUTAS VERMELHAS 12DPX12X30G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MORANGO 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MORANGO 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MORANGO SORTIDA 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA MORANGO SORTIDA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA SORTIDA AMARELA 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA SORTIDA FRUTAS VERDE 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA UVA 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA UVA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'BALA TRIBALA YOGURTE MORANGO 10PCTX500G', grupo: 'PECCIN SA' },
    { nome: 'BALA ZAZA SORTIDA 32PCTX100G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG BLACK 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG BLUE FRAMBOESA 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG ENERGY 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG HORTELA 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG MELANCIA 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG MENTA AZUL 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG MORANGO 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG NITROFERAS 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG NITROFERAS ACIDO 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG NITROFERAS ICE 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG TROPICAL 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG TUTTI-FRUTTI 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'CHICLE BLONG UVA 24DPX40X200G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO MAÇÃ DO AMOR 32PCTX120G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG BLACK 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG BLUE 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG CEREJA 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG ENERGY 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG ENERGY MIX 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG MELANCIA 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG MORANGO 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG NITOSFERA12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG SOUR SORTIDO 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG TUTTI-FRUTTI 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN BLONG UVA 12PCTX672G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN FANTASY 16PCTX600G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN FRAMBOESA DO AMOR 16PCTX480G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN MAÇA DO AMOR 16PCTX480G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN MAÇA VERDE DO AMOR 16PCTX480G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN MORANGO DO AMOR 16PCTX480G', grupo: 'PECCIN SA' },
    { nome: 'PIRULITO PECCIN UVA DO AMOR 16PCTX480G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO ALLEGRO CHOC AO LEITE 8DISPX16UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO ALLEGRO CHOCOLATE BCO C/ AMENDOIM 8DISPX16UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES AO LEITE POUCH 20UNX120G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES AVELA POUCH 20UNX120G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES BCO-DARK POUCH 20UNX120G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES DARK 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES DUO POUCH 20UNX120G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES MOUSSE MARACUJA 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO BITES TORTA LIMAO 8DPX12UNX40G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MASSIMO BRANCO C/ COOKIES 8DPX15UNX25G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MASSIMO DARK 8DPX15UNX25G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MINI BRANCO DARK 6PCTX700G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MINI CHOCOLATE 6PCTX700G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MINI SOBREMESAS 6PCTX800G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO MOMENTOS 24DISPX12UNX14G 168G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO SPECIALE PISTACHE C/AVELAS 8DISPX12UNX26G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CARAMELO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CHEESECAKE DE MORANGO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER CHOCOLATE BRANCO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER DARK 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER DUO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER MILK 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER MORANGO 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER MOUSSE MARACUJA 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER PISTACHE 8DPX16UNX29G', grupo: 'PECCIN SA' },
    { nome: 'TRENTO WAFER TRUFA 8DPX16UNX29G', grupo: 'PECCIN SA' },
    // PERFETTI VAN MELLE
    { nome: 'CHUPA CHUPS SORTIDO BAG 50 UN C/20', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'CHUPA CHUPS SORTIDO POTE 100 UN C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA MAST. BAG MORANGO 12X92G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA MAST. FRUIT MIX BAG 12X92G', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA MAST. MORANGO VIT C 1X3 (SM) C/42', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'FRUITTELLA SWIRL FRAMB. VIT C 10X15 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'GARRAFA DIVE FRESH SPEARMINT 21X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'GARRAFA DIVE FRESH TROPICAL 21X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS BERRY BAG MIX 12X62,1GR', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS CLEAR BREATH MINT BIG GRF 150X10', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS CLEAR BREATH PEPPERMINT LATA 50X12 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA BIG FRESH MINT 46X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA BIG TUTTI FRESH 46X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GOMA GARRAFA BIG WINTERGREEN 46X6 C/6', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GUM GARRAFA MINI BUBLE MINT 6DPX10X10UN', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GUM GARRAFA MINI FRESH MINT 6DPX10X10UN', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS GUM GARRAFA MINI SPEARMINT 6DPX10X10UN', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS MINT FLAT 12DPX9UNID', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS MORANGO BIG GRF 150X10', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS KISS MORANGO FLAT 12DPX9UNID', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS PF STICK GOMA FRESH MINT 8X14 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS PF STICK GOMA WINTERGREEN 8X14 C/12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK FRUIT 1X3 (SM) C/42', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK MINT 1X3 (SM) C/42', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'MENTOS STICK RAINBOW 1X3 (SM) C/42', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH MINT REFIL 28P 56G C/48', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH MONO MINT/WINTERGREEN SACHE 60P-2GX12DP', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH MONO TUTIFRUTTI SACHE 4X15X12', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESH WITGREEN REFIL 28P 56G C/ 48', grupo: 'PERFETTI VAN MELLE' },
    { nome: 'PURE FRESHMINT MONO 12DPX60P', grupo: 'PERFETTI VAN MELLE' },
    // VAPZA
    { nome: '7 GRAOS ORGANICO VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'ARROZ INTEGRAL ORGANICO 18X250G', grupo: 'VAPZA' },
    { nome: 'ARROZ INTEGRAL STD VAPZA 10X200G', grupo: 'VAPZA' },
    { nome: 'BATATA DOCE EM CUBOS VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'BATATA ROSTI VAPZA 12X400G', grupo: 'VAPZA' },
    { nome: 'CANJA COM ARROZ INTEGRAL STD VAPZA 7X400G', grupo: 'VAPZA' },
    { nome: 'CANJA COM ARROZ INTEGRAL VAPZA 12X400G', grupo: 'VAPZA' },
    { nome: 'CANJICA COM DOCE DE LEITE STD VAPZA 10X250G', grupo: 'VAPZA' },
    { nome: 'CANJICA VAPZA 24X500G', grupo: 'VAPZA' },
    { nome: 'CARNE SECA DESFIADA VAPZA 12X400G', grupo: 'VAPZA' },
    { nome: 'FEIJAO CARIOCA ORGANICO VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'FEIJAO CARIOCA STD VAPZA 10X200G', grupo: 'VAPZA' },
    { nome: 'FEIJAO CARIOCA VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'FEIJAO CARIOCA VAPZA SO AQUECER 18X250G', grupo: 'VAPZA' },
    { nome: 'FEIJAO PRETO ORGANICO VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'FEIJAO PRETO VAPZA 10X200G', grupo: 'VAPZA' },
    { nome: 'FEIJAO PRETO VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'FEIJAO PRETO VAPZA SO AQUECER 18X250G', grupo: 'VAPZA' },
    { nome: 'FEIJOADA STD VAPZA 10X250G', grupo: 'VAPZA' },
    { nome: 'FEIJOADA VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'FRANGO DESFIADO VAPZA 12X400G', grupo: 'VAPZA' },
    { nome: 'GRAO DE BICO STD VAPZA 10X200G', grupo: 'VAPZA' },
    { nome: 'GRAO DE BICO VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'LENTILHA COM BACON STD VAPZA 10X250G', grupo: 'VAPZA' },
    { nome: 'LENTILHA VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'MANDIOCA AIPIM VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'MANDIOQUINHA SALSA BAROA VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'MIX DE QUINOA ORGANICA VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'PICADINHO DE CARNE COM ARROZ E FEIJAO VAPZA 10X370G', grupo: 'VAPZA' },
    { nome: 'QUINOA BRANCA ORGANICA VAPZA 18X250G', grupo: 'VAPZA' },
    { nome: 'SELETA DE LEGUMES VAPZA 12X500G', grupo: 'VAPZA' },
    { nome: 'STROGONOFF DE CARNE STD VAPZA 10X250G', grupo: 'VAPZA' },
    { nome: 'STROGONOFF DE FRANGO STD VAPZA 10X250G', grupo: 'VAPZA' },
    // BASTON - Produtos novos
    { nome: 'ADIT.RAD.TECBRIL LONG LIFE PU ROSA 12X500ML', grupo: 'BASTON' },
    { nome: 'ADIT.RAD.TECBRIL LONG LIFE ROSA MONTADORA 12X1L', grupo: 'BASTON' },
    { nome: 'AGUA DESMINERALIZADA TECBRIL 12X1L', grupo: 'BASTON' },
    { nome: 'BORRACHA LIQUIDA BRANCA CHEMICOLOR 6X400ML/240G', grupo: 'BASTON' },
    { nome: 'BRILHO INOX SUPER DOM 6X300ML/200G', grupo: 'BASTON' },
    { nome: 'COLA CHEMICOLOR AEROSSOL 06X250ML/150G', grupo: 'BASTON' },
    { nome: 'DESENGRIPANTE CHEMICOLOR ORANGE 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'DESENGRIPANTE TECBRIL BRIL LUB FIT ORANGE 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'DESO ABOVE FEEL FREE ZERO S/ALU MEN 12X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ABOVE FEEL FREE ZERO S/ALU WOMEN 12X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMA WOMEN CLAREADOR 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL MEN 96H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL S/PERF 96H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT ABOVE DERMACLINICAL WOMEN 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS CANDY 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS DOLCE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS FRESH 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT AERO ABOVE FEM. CLAS LADY 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE BISNAGA CLAS.CANDY 24X50G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE BISNAGA DERMA CLAR SERUM 24X50G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CLAS S/PERFUME 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CREAM ORIGINAL 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE CREAM VANILLA 72H 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS CARBON ACTIVE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS HURRICANE 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS OCEAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE ELEMENTS VULCAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTR INVISIBLE MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME BLACK MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME MOV MEN 72H AC 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE EXTREME SPORT MEN 72H AL 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE INVISIBLE WOMAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE MAXX CREAM ORIGINAL L250ML P150ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE SPORT ENERGY MEN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.ABOVE SPORT ENERGY WOMAN 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'DESO ANT.CREME ABOVE CLAS. S/PERFUME 50G 12UN', grupo: 'BASTON' },
    { nome: 'DESO ANT.CREME ABOVE CLAS. SPORT MEN 50G 12UN', grupo: 'BASTON' },
    { nome: 'DESO ANT.CREME ABOVE CLAS.CANDY WOMEN 50G 12UN', grupo: 'BASTON' },
    { nome: 'DESO ANT.CREME ABOVE ENERGY SPORT MEN 50G 12UN', grupo: 'BASTON' },
    { nome: 'DESO ANT.CREME ABOVE SPORT ENERGY WOMEN 50G 12UN', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE CANDY WOMAN 12X50ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE CREAM ORIGINAL 12X50ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE DERMA CLAREADOR SERUM 72H 12X50ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE EXTR MEN BLACK 12X50ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE SEM PERFUME 12X80ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE SPORT ENERGY MEN 12X50ML', grupo: 'BASTON' },
    { nome: 'DESO ANT.ROLLON ABOVE SPORT ENERGY WOMEN 12X50ML', grupo: 'BASTON' },
    { nome: 'ESPUMA BARBA ABOVE 24X150ML/145G', grupo: 'BASTON' },
    { nome: 'ESPUMA BARBA ABOVE CARVAO ATIVADO 24X150ML/145G', grupo: 'BASTON' },
    { nome: 'ESPUMA DE BARBA ABOVE CARVAO ATIVADO PAGUE 200ML LEVE 250ML', grupo: 'BASTON' },
    { nome: 'ESPUMA LIMPA TUDO GT PREMIUM 12X300ML/170G', grupo: 'BASTON' },
    { nome: 'ESPUMA LIMPADORA TECBRIL 12X300ML/290G', grupo: 'BASTON' },
    { nome: 'GAS DE FOGAREIRO SUPER DOM 06X400ML/200G', grupo: 'BASTON' },
    { nome: 'KIT ABOVE PROT SOLAR FPS50 150ML+PROTETOR SOLAR CREME 50G', grupo: 'BASTON' },
    { nome: 'KIT ABOVE SH ANTICASPAS FRESH E MENTOL 325ML+ESP.DE BARBEAR', grupo: 'BASTON' },
    { nome: 'KIT ABOVE SHAMPOO+COND HIDRATACAO 12UNID', grupo: 'BASTON' },
    { nome: 'KIT ABOVE SHAMPOO+COND NUTRICAO 12UNID', grupo: 'BASTON' },
    { nome: 'KIT ABOVE SHAMPOO+COND RECONSTRUCAO 12UNID', grupo: 'BASTON' },
    { nome: 'LIMPA AIR FRYER SUPER DOM 6X250ML', grupo: 'BASTON' },
    { nome: 'LIMPA BOX SUPER DOM 12X500ML/300G', grupo: 'BASTON' },
    { nome: 'LIMPA ESTOFADOS SUPER DOM C/ESCOVA 6X300ML/180G', grupo: 'BASTON' },
    { nome: 'LIMPA FORNO SUPER DOM 6X250ML/150G', grupo: 'BASTON' },
    { nome: 'LIMPA GRELHA SUPER DOM 6X250ML/150G', grupo: 'BASTON' },
    { nome: 'LIMPA VIDROS SUPER DOM 12X500ML', grupo: 'BASTON' },
    { nome: 'LUSTRA MOVEIS SUPER DOM 6X250ML/150G', grupo: 'BASTON' },
    { nome: 'MASSAGEADOR ABOVE ICE DOUTORFLAN 12X100ML/65G', grupo: 'BASTON' },
    { nome: 'MATA BARATAS PROINSET 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MATA CUPIM PROINSET 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET 12X600ML/312G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET ACAO TOTAL 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON ACAO TOTAL 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON CITRONELA 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECON S/CHEIRO 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET EMB.ECONOMICA EUCALIPTO 12X350ML/185G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET PROMOCIONAL 12X450ML/330G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET PROMOCIONAL S/CHEIRO 12X450ML/330G', grupo: 'BASTON' },
    { nome: 'MULTI-INSET PROINSET S/CHEIRO 12X250ML/120G', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR CAPIM LIMAO 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR CAPIM LIMÃO 12X400ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR CRAVO E CANELA 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR LAVANDA 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR LAVANDA 12X400ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR MACA E CANELA 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR NEUTRO 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR PETALAS DE ROSAS 12X400ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR PETALAS ROSAS 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR TALCO 12X250ML', grupo: 'BASTON' },
    { nome: 'NEUTRALIZADOR PURO AR TALCO 12X400ML', grupo: 'BASTON' },
    { nome: 'ODORIZADOR PURO AR 12ML MINI LEV3 PAG2 LAVANDA', grupo: 'BASTON' },
    { nome: 'ODORIZADOR PURO AR 12ML MINI LEV3 PAG2 TALCO', grupo: 'BASTON' },
    { nome: 'ODORIZADOR TEC FRESH CARD MISTO TECBRIL 4DPX24X4G', grupo: 'BASTON' },
    { nome: 'PROTETOR SOLAR ABOVE FPS 30 6X350ML/250G', grupo: 'BASTON' },
    { nome: 'PROTETOR SOLAR ABOVE FPS 50 6X350ML/250G', grupo: 'BASTON' },
    { nome: 'PROTETOR SOLAR ABOVE FPS50 CR ROSTO/CORPO 12X50G', grupo: 'BASTON' },
    { nome: 'PROTETOR SOLAR ABOVE SPORT FPS80 12X150ML/120G', grupo: 'BASTON' },
    { nome: 'REPELENTE ABOVE AERO 24X150ML/120G', grupo: 'BASTON' },
    { nome: 'REPELENTE ABOVE AERO C/ICARIDINA 24X150ML/90G', grupo: 'BASTON' },
    { nome: 'REPELENTE ABOVE KIDS 12X100ML', grupo: 'BASTON' },
    { nome: 'REPELENTE ABOVE SPRAY ADULTO 12X200ML', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CANDY 72X75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CANDY PACKS L6 P4 72UN', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CREAM ORIGINAL 72X75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CREAM ORIGINAL PACKS L6 PG4 75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CREAM VANILLA 72X75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE CREAM VANILLA PACKS L6 PG4 75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE EXTREME BLACK 72X75G', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE EXTREME BLACK PACKS L6 P4 72UN', grupo: 'BASTON' },
    { nome: 'SABONETE BARRA ABOVE EXTREME MOVEMENT 72X75G', grupo: 'BASTON' },
    { nome: 'SABONETE INTIMO ABOVE 12X200ML', grupo: 'BASTON' },
    { nome: 'SABONETE INTIMO ABOVE PACKS DUO 200ML 12UN', grupo: 'BASTON' },
    { nome: 'SHAMPOO ABOVE MASC. ANTICASPA 12X220ML', grupo: 'BASTON' },
    { nome: 'SHAMPOO ABOVE MASC. ANTICASPA 12X325ML', grupo: 'BASTON' },
    { nome: 'TALCO ANTISSEPTICO ABOVE PE PROT CANFORADO 12X100G', grupo: 'BASTON' },
    { nome: 'TALCO ANTISSEPTICO ABOVE PE PROT TRADIC 12X100G', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML ALUMINIO 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML BRANCO BRILHANTE 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML BRANCO FOSCO 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML FUNDO CINZA 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML PRETO BRILHANTE 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML PRETO FOSCO 6X250ML', grupo: 'BASTON' },
    { nome: 'TINTA CHEMICOLOR 250ML VERNIZ BRILHANTE 6X250ML', grupo: 'BASTON' },
    // AB MAURI - Produtos novos
    { nome: 'AROMA BAUNILHA GRAN FINALE FLEISCHMANN 4X12X30ML', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE 85% AMAZONIA 6X14X80G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE FLOW AMENDOAS 6X14X90G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE FLOW AO LEITE 6X14X90G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE FLOW BRANCO 6X14X90G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE FLOW CAR FLOR SAL 6X14X90G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE WAFER 70% 12DPX12X25G', grupo: 'AB MAURI' },
    { nome: 'BARRA CHOCO DANKE WAFER AO LEITE 12DPX12X25G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOC 63% AVELA DANKE 12X72G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCO SORTIDO LT MAES NAMOR 6X108G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOCLATE 70% DANKE 12X72G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE 70% 6X162G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE AO LEITE 4X450G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE AO LEITE DANKE 12X72G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE AO LEITE6X162G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE BRANCO DANKE 12X72G', grupo: 'AB MAURI' },
    { nome: 'BOMBOM DANKE CHOCOLATE CORACAO 6X117G', grupo: 'AB MAURI' },
    { nome: 'CHOCOLATE EM PO SOLUVEL 32% GRAN FINALE FLEISCHMANN 200G', grupo: 'AB MAURI' },
    { nome: 'CHOCOLATE EM PO SOLUVEL 50% GRAN FINALE FLEISCHMANN 200G', grupo: 'AB MAURI' },
    { nome: 'CREME CHANTILLY GRAN FINALE FLEISCHMANN TP 12UNI 1L', grupo: 'AB MAURI' },
    { nome: 'CREME CHANTILLY GRAN FINALE FLEISCHMANN TP 12UNI 500ML', grupo: 'AB MAURI' },
    { nome: 'CREME CROCANTE OVOMALTINE 6PTX530G', grupo: 'AB MAURI' },
    { nome: 'CREME CULINARIO GRAN FINALE FLEISCHMANN TP 12X1L', grupo: 'AB MAURI' },
    { nome: 'FERMENTO BIOL SECO FLEISCHMANN 4DPX16 PCT 125G', grupo: 'AB MAURI' },
    { nome: 'FERMENTO BIOL SECO FLEISCHMANN 4DPX16X30G L3P2', grupo: 'AB MAURI' },
    { nome: 'FERMENTO BIOLOGICO 500G MD 20X500G', grupo: 'AB MAURI' },
    { nome: 'FERMENTO PO QUIMICO FLEISCHMANN 72 PT 100G', grupo: 'AB MAURI' },
    { nome: 'GELATINA GRAN FINALE FLEISCHMANN SEM SABOR 30X24G', grupo: 'AB MAURI' },
    { nome: 'MELHORADOR FAR MAIS MACIO FLEISCHMANN 6DPX32X10G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM AIPIM 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM BROWNIE 20X400G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM CHOCO-UP 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM CHOCOMOUSSE 400G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM COCO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM EXTRACREM CHOCOMOUSSE 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM LARANJA CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM LIMAO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM MILHO CREMOSO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHM PAO DE QUEIJO 20X310G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CENOURA-UP 390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CHEESECAKE 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CHOCOLATE 390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CHOCOLATE ADOCE JEITO 12X230G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN CHOCOLATE FONTE DE PROT 12X230G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN PETIT GATEAU 20X350G', grupo: 'AB MAURI' },
    { nome: 'MISTURA BOLO FLEISCHMANN TORTA DE LIMAO 20X390G', grupo: 'AB MAURI' },
    { nome: 'MISTURA PAO DE QUEIJO 12X250G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 10MM 12X750G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 12X190G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 12X300G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 15PCT 600G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE 5MM 12X750G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE FLOCOS CROCANTE POTE 24X400G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE ROCKS 32X110G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE ROCKS 6DPX18X40G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE ROCKS MESCLADO 32X110G', grupo: 'AB MAURI' },
    { nome: 'OVOMALTINE ROCKS MESCLADO 6DPX18X40G', grupo: 'AB MAURI' },
    { nome: 'PACK MADEIRA TWININGS 108G 6 DP C/10', grupo: 'AB MAURI' },
    { nome: 'SUPER FERMENTO FLEISCHMANN 6DPX32X13G', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA CAMOMILA, MEL E BAUNILHA 15G 12XDP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA DE CAMOMILA 10G 12XDP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA DE HORTELA 17,5G DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA ERVA DOCE 20G 12UN C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA FRUTAS SILVESTRES 20G 12UND C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA LIMAO COM GENGIBRE 15G 12UNID C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA MISTO CAM/CAN/MAÇA 15G DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA MISTO LAR/MAN/CAN 18G DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA MISTO LIMAO FRAMBOESA 15G 12UNID C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA MISTO MORANGO E MANGA 15G 12 UNID C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA PRETO EARL GREY 20G DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA PRETO ENGLISH BREAKFAST 20G DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA PRETO LADY GREY 20G 12UNID C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA PRETO SABOR FT VERMELHAS 20G 12 DP C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA VERDE 20G 12UNID C/10', grupo: 'AB MAURI' },
    { nome: 'TWININGS CHA VERDE MT HORTELA 20G 12 UNID DP C/10', grupo: 'AB MAURI' }
];

function aplicarTema(temaEscuro) {
    const body = document.body;
    const button = document.getElementById('themeToggleBtn');
    const icon = document.getElementById('themeIcon');
    const label = document.getElementById('themeLabel');

    body.classList.toggle('dark-theme', temaEscuro);
    if (localStorage) {
        localStorage.setItem('temaPreferido', temaEscuro ? 'dark' : 'light');
    }

    if (button && icon && label) {
        button.classList.toggle('btn-light', !temaEscuro);
        button.classList.toggle('btn-dark', temaEscuro);
        icon.className = temaEscuro ? 'bi bi-sun-fill' : 'bi bi-moon-stars-fill';
        label.textContent = temaEscuro ? 'Claro' : 'Escuro';
    }
}

function iniciarTema() {
    const temaSalvo = localStorage.getItem('temaPreferido');
    const usaTemaEscuro = temaSalvo === 'dark' || (!temaSalvo && window.matchMedia('(prefers-color-scheme: dark)').matches);
    aplicarTema(usaTemaEscuro);

    const button = document.getElementById('themeToggleBtn');
    if (button) {
        button.addEventListener('click', () => {
            const proximoTema = !document.body.classList.contains('dark-theme');
            aplicarTema(proximoTema);
        });
    }
}

// Função para carregar o cabeçalho
function carregarHeader() {
    fetch('header.html')
        .then(response => response.text())
        .then(data => {
            headerContainer.innerHTML = data;
            iniciarTema();
        })
        .catch(error => console.error('Erro ao carregar o cabeçalho:', error));
}

// Função para carregar o rodapé
function carregarFooter() {
    fetch('footer.html')
        .then(response => response.text())
        .then(data => footerContainer.innerHTML = data)
        .catch(error => console.error('Erro ao carregar o rodapé:', error));
}

// Carregar o cabeçalho, o rodapé e os produtos quando a página for carregada
document.addEventListener('DOMContentLoaded', function () {
    carregarHeader();
    carregarFooter();
    renderizarProdutos();
    carregarDadosTabela();
});

function linhaTemCadastro(linha) {
    const colunas = linha.querySelectorAll('td');
    if (colunas.length < 3) return false;

    const estoque = colunas[1].innerText.trim();
    const sugestao = colunas[2].innerText.trim();

    return estoque !== '' || sugestao !== '';
}

function aplicarFiltros() {
    const filtroGrupo = grupoProduto ? grupoProduto.value : '';
    const termoBusca = searchInput ? searchInput.value.trim().toLowerCase() : '';

    document.querySelectorAll('#tabelaProdutos tr').forEach(linha => {
        const grupoLinha = linha.getAttribute('data-grupo');
        const nomeProduto = linha.querySelector('td')?.innerText.toLowerCase() || '';

        let exibida = true;

        if (filtroGrupo !== '' && grupoLinha !== filtroGrupo) {
            exibida = false;
        }

        if (termoBusca && !nomeProduto.includes(termoBusca)) {
            exibida = false;
        }

        if (apenasCadastradosAtivado && !linhaTemCadastro(linha)) {
            exibida = false;
        }

        linha.style.display = exibida ? '' : 'none';
    });
}

// Filtrar produtos pelo grupo selecionado
if (grupoProduto) {
    grupoProduto.addEventListener('change', function () {
        aplicarFiltros();
    });
}

if (btnApenasCadastrados) {
    btnApenasCadastrados.addEventListener('click', function () {
        apenasCadastradosAtivado = true;
        btnApenasCadastrados.classList.add('active');
        btnTodosProdutos.classList.remove('active');
        aplicarFiltros();
    });
}

if (btnTodosProdutos) {
    btnTodosProdutos.addEventListener('click', function () {
        apenasCadastradosAtivado = false;
        btnTodosProdutos.classList.add('active');
        btnApenasCadastrados.classList.remove('active');
        aplicarFiltros();
    });
}

function renderizarProdutos() {
    if (!tabelaProdutos) return;

    localStorage.removeItem('dadosTabela');
    tabelaProdutos.innerHTML = '';

    produtosIniciais.forEach(produto => {
        const linha = document.createElement('tr');
        linha.setAttribute('data-grupo', produto.grupo);

        const celulaNome = document.createElement('td');
        celulaNome.textContent = produto.nome;

        const celulaEstoque = document.createElement('td');
        celulaEstoque.contentEditable = true;
        celulaEstoque.dataset.campo = 'estoque';
        celulaEstoque.className = 'editable-cell';

        const celulaSugestao = document.createElement('td');
        celulaSugestao.contentEditable = true;
        celulaSugestao.dataset.campo = 'sugestao';
        celulaSugestao.className = 'editable-cell';

        [celulaEstoque, celulaSugestao].forEach(celula => {
            celula.addEventListener('input', salvarDadosTabela);
        });

        linha.appendChild(celulaNome);
        linha.appendChild(celulaEstoque);
        linha.appendChild(celulaSugestao);
        tabelaProdutos.appendChild(linha);
    });
}

// Função de pesquisa
if (searchInput) {
    searchInput.addEventListener('input', function () {
        aplicarFiltros();
    });
}

// Compartilhar no WhatsApp
if (shareButton) {
    shareButton.addEventListener('click', function () {
        let message = 'Segue Levantamento de Estoque e Sugestão de pedido:\n------------------------\n\n';
        document.querySelectorAll('#tabelaProdutos tr').forEach(linha => {
            const colunas = linha.querySelectorAll('td');
            if (colunas.length < 3) return; // Garante que há colunas suficientes

            const nomeProduto = colunas[0].innerText;
            const estoque = colunas[1].innerText.trim();
            const sugestao = colunas[2].innerText.trim();

            if (estoque !== '' && sugestao !== '') {
                message += `Produto: ${nomeProduto}\nEstoque: ${estoque}\nSugestão: ${sugestao}\n\n------------------------\n`;
            }
        });

        if (message === 'Segue Levantamento de Estoque e Sugestão de pedido:\n------------------------\n\n') {
            alert('Falta produto preenchido para compartilhar. Preencha as 2 colunas, Estoque e sugestão, mesmo que seja 0');
            return;
        }

        window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
    });
}

// Salvar dados localmente
function salvarDadosTabela() {
    const dados = [];
    document.querySelectorAll('#tabelaProdutos tr').forEach(linha => {
        const colunas = linha.querySelectorAll('td');
        if (colunas.length < 3) return;

        dados.push({
            produto: colunas[0].innerText,
            estoque: colunas[1].innerText,
            sugestao: colunas[2].innerText
        });
    });

    localStorage.setItem('dadosTabela', JSON.stringify(dados));
}

// Carregar dados salvos
function carregarDadosTabela() {
    const dadosSalvos = localStorage.getItem('dadosTabela');
    if (!dadosSalvos) return;

    const dados = JSON.parse(dadosSalvos);
    document.querySelectorAll('#tabelaProdutos tr').forEach((linha, index) => {
        const colunas = linha.querySelectorAll('td');
        if (colunas.length < 3 || !dados[index]) return;

        colunas[1].innerText = dados[index].estoque;
        colunas[2].innerText = dados[index].sugestao;
    });
}

// Botão LIMPAR DADOS
if (limparDadosBtn) {
    limparDadosBtn.addEventListener('click', function () {
        localStorage.removeItem('dadosTabela');
        document.querySelectorAll('#tabelaProdutos tr td:nth-child(2), #tabelaProdutos tr td:nth-child(3)').forEach(td => td.innerText = '');
        alert('Dados apagados!');
    });
}
